openapi: 3.1.0
info:
  title: Fast Admin Webhook API
  version: 0.1.0
tags:
- name: Webhook
paths:
  /webhook/nima:
    post:
      summary: Delete Content And Warn User Route
      operationId: delete_content_and_warn_user_route_webhook_nima_post
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - Webhook
  /webhook/revenuecat:
    post:
      summary: Handle Revenuecat Events
      operationId: handle_revenuecat_events_webhook_revenuecat_post
      parameters:
      - name: authorization
        in: header
        required: false
        schema:
          anyOf:
          - type: string
          - type: 'null'
          title: Authorization
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RevenueCatWebhookPayload'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
      tags:
      - Webhook
components:
  schemas:
    RevenueCatEventType:
      type: string
      enum:
      - TEST
      - INITIAL_PURCHASE
      - NON_RENEWING_PURCHASE
      - RENEWAL
      - PRODUCT_CHANGE
      - CANCELLATION
      - BILLING_ISSUE
      - SUBSCRIBER_ALIAS
      - SUBSCRIPTION_PAUSED
      - UNCANCELLATION
      - TRANSFER
      - SUBSCRIPTION_EXTENDED
      - EXPIRATION
      - TEMPORARY_ENTITLEMENT_GRANT
      - INVOICE_ISSUANCE
      - VIRTUAL_CURRENCY_TRANSACTION
      - EXPERIMENT_ENROLLMENT
      title: RevenueCatEventType
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
        input:
          title: Input
        ctx:
          type: object
          title: Context
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
    RevenueCatCancellationReason:
      type: string
      enum:
      - UNSUBSCRIBE
      - BILLING_ERROR
      - DEVELOPER_INITIATED
      - PRICE_INCREASE
      - CUSTOMER_SUPPORT
      - UNKNOWN
      title: RevenueCatCancellationReason
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    RevenueCatPeriodType:
      type: string
      enum:
      - TRIAL
      - INTRO
      - NORMAL
      - PROMOTIONAL
      - PREPAID
      title: RevenueCatPeriodType
    RevenueCatEvent:
      properties:
        product_id:
          type: string
          title: Product Id
        period_type:
          $ref: '#/components/schemas/RevenueCatPeriodType'
        purchased_at_ms:
          type: integer
          title: Purchased At Ms
        expiration_at_ms:
          anyOf:
          - type: integer
          - type: 'null'
          title: Expiration At Ms
        environment:
          $ref: '#/components/schemas/RevenueCatEnvironment'
        entitlement_ids:
          anyOf:
          - items:
              type: string
            type: array
          - type: 'null'
          title: Entitlement Ids
        transaction_id:
          type: string
          title: Transaction Id
        is_family_share:
          type: boolean
          title: Is Family Share
        country_code:
          type: string
          title: Country Code
        app_user_id:
          type: string
          title: App User Id
        currency:
          type: string
          title: Currency
        is_trial_conversion:
          anyOf:
          - type: boolean
          - type: 'null'
          title: Is Trial Conversion
        price:
          type: number
          title: Price
        price_in_purchased_currency:
          type: number
          title: Price In Purchased Currency
        store:
          $ref: '#/components/schemas/RevenueCatStore'
        takehome_percentage:
          type: number
          title: Takehome Percentage
        offer_code:
          anyOf:
          - type: string
          - type: 'null'
          title: Offer Code
        tax_percentage:
          type: number
          title: Tax Percentage
        commission_percentage:
          type: number
          title: Commission Percentage
        renewal_number:
          anyOf:
          - type: integer
          - type: 'null'
          title: Renewal Number
        type:
          $ref: '#/components/schemas/RevenueCatEventType'
        cancel_reason:
          anyOf:
          - $ref: '#/components/schemas/RevenueCatCancellationReason'
          - type: 'null'
        expiration_reason:
          anyOf:
          - $ref: '#/components/schemas/RevenueCatExpirationReason'
          - type: 'null'
      additionalProperties: true
      type: object
      required:
      - product_id
      - period_type
      - purchased_at_ms
      - environment
      - transaction_id
      - is_family_share
      - country_code
      - app_user_id
      - currency
      - price
      - price_in_purchased_currency
      - store
      - takehome_percentage
      - tax_percentage
      - commission_percentage
      - type
      title: RevenueCatEvent
    RevenueCatWebhookPayload:
      properties:
        event:
          $ref: '#/components/schemas/RevenueCatEvent'
        api_version:
          type: string
          title: Api Version
      additionalProperties: true
      type: object
      required:
      - event
      - api_version
      title: RevenueCatWebhookPayload
    RevenueCatEnvironment:
      type: string
      enum:
      - PRODUCTION
      - SANDBOX
      title: RevenueCatEnvironment
    RevenueCatStore:
      type: string
      enum:
      - AMAZON
      - APP_STORE
      - MAC_APP_STORE
      - PADDLE
      - PLAY_STORE
      - PROMOTIONAL
      - RC_BILLING
      - ROKU
      - STRIPE
      - TEST_STORE
      title: RevenueCatStore
    RevenueCatExpirationReason:
      type: string
      enum:
      - UNSUBSCRIBE
      - BILLING_ERROR
      - DEVELOPER_INITIATED
      - PRICE_INCREASE
      - CUSTOMER_SUPPORT
      - UNKNOWN
      title: RevenueCatExpirationReason
