openapi: 3.1.0
info:
  title: Fast Admin FastAPI API
  version: 0.1.0
tags:
- name: FastAPI
paths:
  /:
    get:
      summary: Home
      operationId: home__get
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
      tags:
      - FastAPI
